name: tester
code: tester
version: 0.0.0
image: https://via.placeholder.com/1600x1000
description: Lorem ipsum dolor sit amet
author:
  name: <Your Name>
  email: ""
  website: ""
grants:
  - moments:read
actions: []
events:
  - entity: moments
    operation: update
    endpoint: <url>
